### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by filenkoB** [filenkoB/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by AAndromedAA** [comment]
I am an avid gamer. This should come as no surprise since even sold a video game called Blastar for $500 when I was merely 12 years old, and once worked at a gaming start-up called Rocket Science. My favorites include Deus Ex, Fallout and BioShock.

I also likes to throw parties. One of my previous birthdays and office celebrations have included a rented castle in England where the guests played hide-and-seek and a costume party in Venice where I dressed as a knight.

Also I still find time to binge-watch series on Netflix and HBO. I revealed before that I have seen Silicon Valley, which centers on a fictional tech company, and Black Mirror, which explores humanity‘s relationship to technology

I enjoy anime and loved the Makoto Shinkai movie Your Name. I am also a fan of Studio Ghibli movies like Spirited Away and Princess Mononoke. In an interview with Maureen Dowd at The New York Times, I said that I spent the weekend watching anime (including Death Note and Evangelion) with my girlfriend Grimes.

**Comment by Marsichek2** [comment]
I am an avid gamer. This should come as no surprise since even sold a video game called Blastar for $500 when I was merely 12 years old, and once worked at a gaming start-up called Rocket Science. My favorites include Deus Ex, Fallout and BioShock.

I also likes to throw parties. One of my previous birthdays and office celebrations have included a rented castle in England where the guests played hide-and-seek and a costume party in Venice where I dressed as a knight.

Also I still find time to binge-watch series on Netflix and HBO. I revealed before that I have seen Silicon Valley, which centers on a fictional tech company, and Black Mirror, which explores humanity‘s relationship to technology

I enjoy anime and loved the Makoto Shinkai movie Your Name. I am also a fan of Studio Ghibli movies like Spirited Away and Princess Mononoke. In an interview with Maureen Dowd at The New York Times, I said that I spent the weekend watching anime (including Death Note and Evangelion) with my girlfriend Grimes.

**Comment by filenkoB** [comment]
Very great information!

**Comment by filenkoB** [comment]
Add please something about his languages and character.

**Comment by Marsichek2** [comment]
Languages:
I speak only English language.

Character:
As a true lider, I have the following character traits:
Entrepreneurial Spirit.
Passion for Innovation.
Positive Energy.
Strategic Direction.
Personal Integrity/Influence.
